version: '3.9'

services:
  database:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: ecommerce_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wpsite

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80 
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_app
    depends_on:
      - database
    volumes:
      - .:/var/www/html
    ports:
      - "8001:80"
    networks:
      - wpsite

networks:
  wpsite:
volumes:
  db_data: